### ISSUE TITLE
Crash everytime on eqsp32.getPin(EQ_RS485_XX)

### ISSUE THREAD

**Issue by khoapmd** [Erqos/EQSP32#2]
EQSP32 initialized successfully.
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x42088fb0  PS      : 0x00060a30  A0      : 0x82081649  A1      : 0x3fcebeb0  
A2      : 0x3fc97c84  A3      : 0x00000051  A4      : 0x00000015  A5      : 0x00000017  
A6      : 0x00000051  A7      : 0xffffffff  A8      : 0x60009050  A9      : 0x3fcebe90  
A10     : 0x0000003c  A11     : 0x0000001f  A12     : 0x00000000  A13     : 0x00000000

**Comment by Erqos** [comment]
Thank you for raising this issue.
It has been addressed and resolved in the **v0.4.0 release.**
